export type caseManagerForm = {
    month: string,
    cm_id: string,
    year: string,
    total_number_of_contacts: string,
    women_birthdays: string,
    kid_birthdays: string,
    birthday_cards: string,
    birthday_cards_value: string,
    food_cards: string,
    food_cards_value: string,
    bus_passes: string,
    bus_passes_value: string,
    gas_cards: string,
    gas_cards_value: string,
    women_healthcare_referrals: string,
    kid_healthcare_referrals: string,
    women_counseling_referrals: string,
    kid_counseling_referrals: string,
    babies_born: string,
    women_degrees_earned: string,
    women_enrolled_in_school: string,
    women_licenses_earned: string,
    reunifications: string,
    number_of_interviews_conducted: string,
    number_of_positive_tests: string,
    number_of_ncns: string,
    number_of_others: string,
    number_of_interviews_accpeted: string,
};

export type caseManagers = {
    id: string,
    firstName: string,
    lastName: string,
}