type Nullable<T> = T | null;

export type Client = {
  id: number;
  firstName: string;
  lastName: string;
  phoneNumber: Nullable<string>;
  email: Nullable<string>;
  caseManagerFirstName: string;
  caseManagerLastName: string;
  entranceDate: Nullable<string>;
  exitDate: Nullable<string>;
  dateOfBirth: Nullable<string>;
  bedNights: Nullable<number>;
  bedNightsChildren: Nullable<number>;
  createdBy: string;
  grant: Nullable<string>;
  age: Nullable<number>;
  emergencyContactName: Nullable<string>;
  emergencyContactPhoneNumber: Nullable<string>;
  medical: Nullable<boolean>;
  estimatedExitDate: Nullable<string>;
  pregnantUponEntry: Nullable<boolean>;
  disabledChildren: Nullable<boolean>;
  ethnicity: Nullable<string>;
  race: Nullable<string>;
  cityOfLastPermanentResidence: Nullable<string>;
  priorLiving: Nullable<string>;
  priorLivingCity: Nullable<string>;
  shelterInLastFiveYears: Nullable<boolean>;
  homelessnessLength: Nullable<number>;
  chronicallyHomeless: Nullable<boolean>;
  attendingSchoolUponEntry: Nullable<boolean>;
  employementGained: Nullable<boolean>;
  reasonForLeaving: Nullable<string>;
  specificReasonForLeaving: Nullable<string>;
  specificDestination: Nullable<string>;
  savingsAmount: Nullable<string>;
  attendingSchoolUponExit: Nullable<boolean>;
  reunified: Nullable<boolean>;
  successfulCompletion: Nullable<boolean>;
  destinationCity: Nullable<string>;
  locationName: string;
  status: string;
  unitName: string;
  comments: Nullable<string>;
}
