DROP TABLE IF EXISTS initial_interview CASCADE;

CREATE TYPE marital_status AS ENUM ('single', 'married', 'divorced', 'widowed');

CREATE TYPE ethnicity AS ENUM ('Non-Hispanic', 'Hispanic', 'Refused');

CREATE TABLE initial_interview (
    id SERIAL PRIMARY KEY NOT NULL, 
    applicant_type VARCHAR(256) NOT NULL,
    name VARCHAR(256) NOT NULL,
    age INT NOT NULL,
    date DATE NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    marital_status marital_status NOT NULL,
    date_of_birth DATE NOT NULL,
    email VARCHAR(32) NOT NULL,
    ssn_last_four INT NOT NULL,
    ethnicity ethnicity NOT NULL,
    veteran BOOLEAN NOT NULL,
    disabled BOOLEAN NOT NULL,
    current_address VARCHAR(256) NOT NULL,
    last_perm_address VARCHAR(256) NOT NULL,
    reason_for_leaving_perm_address VARCHAR(256) NOT NULL,
    where_reside_last_night VARCHAR(1024) NOT NULL,
    currently_homeless BOOLEAN NOT NULL,
    event_leading_to_homelessness VARCHAR(256),
    how_long_experiencing_homelessness VARCHAR(256) NOT NULL,
    prev_applied_to_cch BOOLEAN NOT NULL,
    when_prev_applied_to_cch VARCHAR(256),
    prev_in_cch BOOLEAN NOT NULL,
    when_prev_in_cch VARCHAR(256),
    child_name VARCHAR(256) NOT NULL,
    child_dob DATE NOT NULL,
    custody_of_child BOOLEAN NOT NULL,
    father_name VARCHAR(256) NOT NULL,
    name_school_children_attend VARCHAR(256) NOT NULL,
    city_of_school VARCHAR(256) NOT NULL,
    how_hear_about_cch VARCHAR(1024) NOT NULL,
    programs_been_in_before VARCHAR(1024) NOT NULL,
    monthly_income NUMERIC NOT NULL,
    sources_of_income VARCHAR(1024) NOT NULL,
    monthly_bills VARCHAR(1024) NOT NULL,
    currently_employed BOOLEAN NOT NULL,
    last_employer VARCHAR(1024) NOT NULL,
    last_employed_date DATE NOT NULL,
    education_history VARCHAR(1024) NOT NULL,
    transportation VARCHAR(256) NOT NULL,
    legal_resident BOOLEAN NOT NULL,
    medical BOOLEAN NOT NULL,
    medical_city VARCHAR(256),
    medical_insurance VARCHAR(256),
    medications VARCHAR(256) NOT NULL,
    domestic_violence_history VARCHAR(256) NOT NULL,
    social_worker VARCHAR(256) NOT NULL,
    social_worker_telephone VARCHAR(10) NOT NULL,
    social_worker_office_location VARCHAR(256) NOT NULL,
    length_of_sobriety VARCHAR(32) NOT NULL,
    last_drug_use VARCHAR(256) NOT NULL,
    last_alcohol_use VARCHAR(256) NOT NULL,
    time_using_drugs_alcohol VARCHAR(256) NOT NULL,
    been_convicted BOOLEAN NOT NULL,
    convicted_reason_and_time VARCHAR(256),
    present_warrant_exist BOOLEAN NOT NULL,
    warrant_county VARCHAR(256) NOT NULL,
    probation_parole_officer VARCHAR(256) NOT NULL,
    probation_parole_officer_telephone VARCHAR(10) NOT NULL,
    personal_references VARCHAR(256) NOT NULL,
    personal_reference_telephone VARCHAR(10) NOT NULL,
    future_plans_goals VARCHAR(1024) NOT NULL,
    last_permanent_residence_household_composition VARCHAR(1024) NOT NULL,
    why_no_longer_at_last_residence VARCHAR(1024) NOT NULL,
    what_could_prevent_homeless VARCHAR(1024) NOT NULL
);

