CREATE TYPE prior_living AS ENUM('Couch', 'DV Shelter', 'Other Shelter', 'Car', 'Hotel', 'Motel', 'Streets', 'Family', 'Friends', 'Prison/Jail', 'Treatment Center');
CREATE TYPE site AS ENUM('Cypress', 'Glencoe', 'Dairyview', 'Bridge', 'Placentia 38')
CREATE TYPE client_grant AS ENUM('Bridge', 'Non-Funded')

DROP TABLE IF EXISTS intake_statistics_form;
CREATE TABLE intake_statistics_form (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    month TEXT NOT NULL,
    case_manager TEXT NOT NULL,
    cm_id INT NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    ethnicity ethnicity NOT NULL,
    race race NOT NULL,
    birthday DATE NOT NULL,
    age INT NOT NULL,
    phone_number VARCHAR(20),
    email VARCHAR(100) NOT NULL,
    emergency_contact_name VARCHAR(32) NOT NULL,
    emergency_contact_phone_number VARCHAR(10) NOT NULL,
    prior_living_situation prior_living,
    entry_date DATE NOT NULL,
    medical BOOLEAN NOT NULL,
    assigned_case_manager VARCHAR(100),
    site site,
    client_grant client_grant,
    cal_optima_funded_site BOOLEAN,
    unique_id VARCHAR(50) UNIQUE NOT NULL,
    disabling_condition_form BOOLEAN NOT NULL,
    family_size INT NOT NULL,
    number_of_children INT NOT NULL,
    number_of_children_with_disability INT NOT NULL,
    pregnant BOOLEAN NOT NULL,
    city_last_permanent_address VARCHAR(100) NOT NULL,
    where_client_slept_last_night VARCHAR(100) NOT NULL,
    last_city_resided VARCHAR(100) NOT NULL,
    last_city_homeless VARCHAR(100) NOT NULL,
    been_in_shelter_last_5_years BOOLEAN NOT NULL,
    number_of_shelters_last_5_years TEXT NOT NULL,
    duration_homeless TEXT NOT NULL,
    chronically_homeless BOOLEAN NOT NULL,
    employed_upon_entry BOOLEAN NOT NULL,
    attending_school_upon_entry BOOLEAN NOT NULL,
    signed_photo_release BOOLEAN NOT NULL,
    high_risk BOOLEAN NOT NULL,
    currently_employed BOOLEAN NOT NULL,
    date_last_employment DATE NOT NULL,
    history_domestic_violence BOOLEAN NOT NULL,
    history_substance_abuse BOOLEAN NOT NULL,
    support_system BOOLEAN NOT NULL,
    support_housing BOOLEAN,
    support_food BOOLEAN,
    support_childcare BOOLEAN,
    diagnosed_mental_health BOOLEAN NOT NULL,
    undiagnosed_mental_health BOOLEAN NOT NULL,
    transportation BOOLEAN NOT NULL,
    convicted_crime BOOLEAN NOT NULL,
    FOREIGN KEY (cm_id) REFERENCES case_managers(id)
);
