DROP TABLE IF EXISTS intake_statistics_form;
CREATE TABLE intake_statistics_form (
	id SERIAL PRIMARY KEY,
	month month NOT NULL,
	cm_id INT,
    grant VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    birthday DATE,
    entry_date DATE,
    exit_date DATE,
    bed_nights INT,
    total_bed_nights_with_children INT,
    family_size INT,
    pregnant_upon_entry BOOLEAN,
    children_disabled_upon_entry BOOLEAN,
    num_disabled_children INT,
    ethnicity ethnicity,
    race race,
    city_of_last_permanent_residence VARCHAR(255),
    prior_living VARCHAR(255),
    shelter_in_last_five_years BOOLEAN,
    homelessness_length INT,
    how_long_homeless INT,
    chronically_homeless BOOLEAN,
    employed_upon_entry BOOLEAN,
    attending_school_upon_entry BOOLEAN,
    employed_upon_entry_or_gained BOOLEAN,
    reason_for_leaving VARCHAR(1024),
    specific_reason_for_leaving VARCHAR(1024),
    specific_destination VARCHAR(64),
    savings_amount NUMERIC(10, 2),
    employed_upon_exit BOOLEAN,
    attending_school_upon_exit BOOLEAN,
    reunified BOOLEAN,
    number_of_children_reunified INT,
    successful_completion BOOLEAN,
	FOREIGN KEY cm_id REFERENCES case_managers(id)
);